services:
  php:
    build: .
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env

  react:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste25
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      postgres:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

